import type { User, Order } from "@/lib/definitions";

export const users: User[] = [
  { id: "1", name: "Ahmed Ali", email: "ahmed.ali@example.com", phone: "555-1111", role: "user" },
  { id: "2", name: "Fatima Zahra", email: "fatima.zahra@example.com", phone: "555-2222", role: "user" },
  { id: "3", name: "Khalid Hassan", email: "khalid.hassan@example.com", phone: "555-3333", role: "user" },
  { id: "4", name: "Adminstrator", email: "admin@abjour.com", phone: "555-4444", role: "admin" },
  { id: "5", name: "User", email: "user@abjour.com", phone: "555-5555", role: "user" },
];

export const orders: Order[] = [
  {
    id: "ORD001",
    userId: "1",
    orderName: "Villa Reception",
    customerName: "Ahmed Ali",
    customerPhone: "555-1234",
    status: "Delivered",
    date: "2024-05-01",
    totalArea: 12.5,
    totalCost: 1500.0,
    openings: [
      {
        serial: "A01",
        abjourType: "Standard",
        color: "Beige",
        codeLength: 2.5,
        numberOfCodes: 50,
        hasEndCap: true,
        hasAccessories: false,
      },
      {
        serial: "A02",
        abjourType: "Narrow",
        color: "White",
        codeLength: 2.0,
        numberOfCodes: 40,
        hasEndCap: true,
        hasAccessories: true,
      },
    ],
    isArchived: true,
  },
  {
    id: "ORD002",
    userId: "2",
    orderName: "Office Windows",
    customerName: "Fatima Zahra",
    customerPhone: "555-5678",
    status: "Processing",
    date: "2024-05-10",
    totalArea: 25.0,
    totalCost: 3200.0,
    openings: [
      {
        serial: "B01",
        abjourType: "Standard",
        color: "Gray",
        codeLength: 3.0,
        numberOfCodes: 60,
        hasEndCap: false,
        hasAccessories: false,
      },
      {
        serial: "B02",
        abjourType: "Standard",
        color: "Gray",
        codeLength: 3.0,
        numberOfCodes: 60,
        hasEndCap: false,
        hasAccessories: false,
      },
      {
        serial: "B03",
        abjourType: "Wide",
        color: "Black",
        codeLength: 4.0,
        numberOfCodes: 80,
        hasEndCap: true,
        hasAccessories: true,
      },
    ],
    isArchived: false,
  },
  {
    id: "ORD003",
    userId: "1",
    orderName: "Bedroom Renovation",
    customerName: "Ahmed Ali",
    customerPhone: "555-1234",
    status: "FactoryShipped",
    date: "2024-05-15",
    totalArea: 8.0,
    totalCost: 950.0,
    openings: [
      {
        serial: "C01",
        abjourType: "Narrow",
        color: "Wood Finish",
        codeLength: 2.0,
        numberOfCodes: 40,
        hasEndCap: true,
        hasAccessories: false,
      },
    ],
    isArchived: false,
  },
  {
    id: "ORD004",
    userId: "3",
    orderName: "New Apartment",
    customerName: "Khalid Hassan",
    customerPhone: "555-9012",
    status: "FactoryOrdered",
    date: "2024-05-20",
    totalArea: 30.2,
    totalCost: 3800.0,
    openings: [
        { serial: "D01", abjourType: "Standard", color: "White", codeLength: 2.8, numberOfCodes: 56, hasEndCap: true, hasAccessories: true },
        { serial: "D02", abjourType: "Standard", color: "White", codeLength: 2.8, numberOfCodes: 56, hasEndCap: true, hasAccessories: true },
        { serial: "D03", abjourType: "Narrow", color: "Silver", codeLength: 1.5, numberOfCodes: 30, hasEndCap: false, hasAccessories: false },
    ],
    isArchived: false,
  },
];
